###
POST http://localhost:9000/api/products HTTP/1.1
Content-Type: application/json

{
			"name": "Prueba2",
			"description": "Prueba2",
			"image": "assets/images/predeterminado.jpg",
			"price": 34,
			"category": "Electronicos",
			"quantity": 23,
			"inventoryStatus": "ENSTOCK",
			"rating": 5
}

###
GET http://localhost:9000/api/products HTTP/1.1

###
GET http://localhost:9000/api/products/63c5d5a969104eaf8b22a06d HTTP/1.1

###
PUT  http://localhost:9000/api/products/63c71556a11c52ea83b656dc HTTP/1.1
Content-Type: application/json

{
	"_id": "63c71556a11c52ea83b656dc",
			"name": "Samsung Galaxy",
			"description": "Smartphone 5G",
			"image": "imagen_galaxy.jpg",
			"price": 88,
			"category": "Electronics",
			"quantity": 10,
			"inventoryStatus": "LOWSTOCK",
			"rating": 5
}

###
DELETE  http://localhost:9000/api/products/63c70ef9a11c52ea83b656cb HTTP/1.1